apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: boutique

resources:
 - namespace.yaml 
 - app-services/
 - https://raw.githubusercontent.com/GoogleCloudPlatform/microservices-demo/main/kubernetes-manifests/redis.yaml
 - frontend-ingress.yaml

