apiVersion: v1
kind: Service
metadata:
  name: grafana-agent
  labels:
    app.k8s.io/name: grafana-agent
spec:
  selector:
    app.k8s.io/name: grafana-agent
  ports:
    - port: 4317
      name: grpc
      targetPort: grpc
    - port: 4318
      name: http
      targetPort: http
